name: startup_repo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.19.0
  http: ^1.2.2
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.0.5
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3
  cached_network_image: ^3.4.0
  flutter_smart_dialog: ^4.9.8+2

  # # Firebase
  # firebase_core: ^3.4.0
  # firebase_analytics: any
  # firebase_messaging: ^15.1.0
  # firebase_crashlytics: ^4.1.0
  # flutter_local_notifications: ^17.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/languages/

